name: 16Blocks
main: de.minestar.sixteenblocks.Core.Core
version: 1.0
commands:
  spawn:
    description: Takes you to the spawn
    usage: /spawn
  info:
    description: Takes you to the infowall
    usage: /info
  save:
    description: Saves the current area as a structure
    usage: /save <Name>
    