name: 16Blocks
main: de.minestar.sixteenblocks.Core.Core
version: 1.0
commands:
  spawn:
    description: Takes you to the spawn
    usage: /spawn
  info:
    description: Takes you to the infowall
    usage: /info
  start:
    description: Gives you an random zone
    usage: /start  
  startauto:
    description: Gives you an random zone
    usage: /startauto      
  starthere:
    description: Gives you the current zone
    usage: /starthere
  home:
    description: Takes you to your area
    usage: /home [Player]    
  delete:
    description: Delete an area
    usage: /delete <Player>    
  ban:
    description: Ban a player and delete the area
    usage: /ban <Player>    
  save:
    description: Saves the current area as a structure
    usage: /save <Name>
  ticket:
    description: Saves the current area as a structure
    usage: /save <Name>
  bug:
    description: Saves the current area as a structure
    usage: /save <Name>
  report:
    description: Saves the current area as a structure
    usage: /save <Name>