name: 16Blocks
main: de.minestar.sixteenblocks.Core.Core
version: ${pom.version}
commands:
  realstop:
    description: Real stop
    usage: /realstop
  realreload:
    description: Real reload
    usage: /realreload
  support:
    description: Joins the support channel
    usage: /support [Player]
  nochat:
    description: Disable the chat
    usage: /nochat
  hidechat:
    description: Disable the chat
    usage: /hidechat
  chat:
    description: Join the normal chat
    usage: /chat 
  livemap:
    description: Creates an URL to the livemap
    usage: /livemap [Player]
  spawn:
    description: Takes you to the spawn
    usage: /spawn
  team:
    description: Takes you to the Team
    usage: /team
  info:
    description: Takes you to the infowall
    usage: /info
  start:
    description: Gives you an random zone
    usage: /start  
  numberize:
    description: Numberize the rows
    usage: /numberize      
  me:
    description: Fix it
    usage: /me     
  startauto:
    description: Gives you an random zone
    usage: /startauto      
  starthere:
    description: Gives you the current zone
    usage: /starthere
  home:
    description: Takes you to your area
    usage: /home [Player]    
  delete:
    description: Delete an area
    usage: /delete <Player>    
  filter:
    description: Reload the filter lists
    usage: /filter
  ban:
    description: Ban a player and delete the area
    usage: /ban <Player>
  chatradius:
    description: Change the chatradius
    usage: /chatradius <Number>    
  kick:
    description: Kick a player from the server
    usage: /kick <Player>    
  unban:
    description: Unban a player
    usage: /unban <Player>  
  supporter:
    description: Toggle a supporter
    usage: /supporter <Player>
  vip:
    description: Toggle a vip
    usage: /vip <Player>    
  save:
    description: Saves the current area as a structure
    usage: /save <Name>
  give:
    description: Tunneling give command
    usage: /give 
  ticket:
    description: Send a bugreport
    usage: /ticket <Message>
  bug:
    description: Send a bugreport
    usage: /bug <Message>
  report:
    description: Send a bugreport
    usage: /report <Message>
  m:
    description: Send a message to the player
    usage: /m <PlayerName> <Message>
  mute:
    description: Mute a player
    usage: /mute <PlayerName>
  w:
    description: Send a message to the player
    usage: /w <PlayerName> <Message>
  r:
    description: Send a message to the player
    usage: /r <Message>
  tp:
    description: Teleport you to a player
    usage: /tp <Player>    
  row:
    description: Jump to a row
    usage: /row <Number>    
  createrow:
    description: Recreate rowstructures
    usage: /createrow <Number>      
  rel:
    description: Reload the server
    usage: /rel
  shutdown:
    description: Stop the server
    usage: /shutdown    
  slots:
    description: Set Slots 
    usage: /slots <Number>
  say:
    description: Broadcast a message 
    usage: /slots <Message>
  broadcast:
    description: Broadcast a message 
    usage: /broadcast <Message>
  cast:
    description: Broadcast a message 
    usage: /cast <Message>
  admins:
    description: Show list of connected supporter
    usage: /admins
  import:
    description: Import the database
    usage: /import    