name: 16Blocks
main: de.minestar.sixteenblocks.Core.Core
version: ${pom.version}
commands:
  spawn:
    description: Takes you to the spawn
    usage: /spawn
  info:
    description: Takes you to the infowall
    usage: /info
  start:
    description: Gives you an random zone
    usage: /start  
  me:
    description: Fix it
    usage: /me     
  startauto:
    description: Gives you an random zone
    usage: /startauto      
  starthere:
    description: Gives you the current zone
    usage: /starthere
  home:
    description: Takes you to your area
    usage: /home [Player]    
  delete:
    description: Delete an area
    usage: /delete <Player>    
  ban:
    description: Ban a player and delete the area
    usage: /ban <Player>
  kick:
    description: Kick a player from the server
    usage: /kick <Player>    
  unban:
    description: Unban a player
    usage: /unban <Player>  
  save:
    description: Saves the current area as a structure
    usage: /save <Name>
  ticket:
    description: Send a bugreport
    usage: /ticket <Message>
  bug:
    description: Send a bugreport
    usage: /bug <Message>
  report:
    description: Send a bugreport
    usage: /report <Message>
  m:
    description: Send a message to the player
    usage: /m <PlayerName> <Message>
  mute:
    description: Send a message to the player
    usage: /m <PlayerName> <Message>    
  w:
    description: Send a message to the player
    usage: /w <PlayerName> <Message>
  r:
    description: Send a message to the player
    usage: /r <Message>
  tp:
    description: Teleport you to a player
    usage: /tp <Player>    
  row:
    description: Jump to a row
    usage: /row <Number>    
  reload:
    description: Reload the server
    usage: /reload       